### ISSUE TITLE
 tcp_proxy_protocol_enable problems

### ISSUE THREAD

**Issue by amatotech** [slush0/stratum#10]
Failed to load application: **init**() got an unexpected keyword argument 'tcp_proxy_protocol_enable'

I keep hitting this same problem. I thought it was a problem with my config file but I have gone over it 100 times. Anyone else running into this? Any solutions known?

**Comment by laugh26** [comment]
AM having this  when i run sudo python setup.py install

Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    use_setuptools()
  File "/home/pool/stratum-mining/externals/stratum/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/pool/stratum-mining/externals/stratum/distribute_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/home/pool/stratum-mining/externals/stratum/distribute_setup.py", line 194, in download_setuptools
    src = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required
