### ISSUE TITLE
Distribute too old

### ISSUE THREAD

**Issue by Bushstar** [slush0/stratum#25]
The version of distribute that comes with this repo is out of date and causes problems on Ubuntu 17.04.

    Installed /usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg
    Traceback (most recent call last):
      File "setup.py", line 18, in <module>
        install_requires=['twisted', 'ecdsa', 'pyopenssl', 'autobahn',]
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 73, in run
      File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 101, in do_egg_install
      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 358, in run

      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 578, in easy_install

      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 630, in install_item

      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 677, in process_distribution

    TypeError: __init__() takes exactly 2 arguments (4 given)

Installing the latest distribute and hacking the one included helps get past the error when installing.

    pip install --upgrade distribute
    Successfully uninstalled distribute-0.6.28
    Successfully installed distribute-0.7.3

**Comment by BlueShrub** [comment]
I'm glad I'm not the only one having this problem.  I'm not getting past it, though.

Can you provide more details on what you meant by "hacking the one included"?

**Comment by Bushstar** [comment]
Remove the distribute_setup.py and edit setup.py to remove these lines.

From 
-from distribute_setup import use_setuptools
-use_setuptools()
-py_modules=['distribute_setup',],

Then run this to make sure that distribute is up-to-date.
pip install --upgrade distribute

Then try installing again with.
sudo python setup.py install

The process is full of errors and a lot of them are not very obvious. Top tip, enable the stratum.log while setting up stratum-mining, it will help.
https://github.com/slush0/stratum-mining/blob/master/conf/config_sample.py#L15

**Comment by machado-rev** [comment]
I know that almost 1 year has passed but I am here to feedback the solution! IT WORKS! 

Thank you
