### ISSUE TITLE
Unable to install python setup.py

### ISSUE THREAD

**Issue by EmelyanovMax** [slush0/stratum#30]
As I run "sudo python setup.py develop"  I get error message
"Extracting in /tmp/tmpEop01P
Now working in /tmp/tmpEop01P/distribute-0.6.28
Building a Distribute egg in /var/www/stratum.local
Traceback (most recent call last):
  File "setup.py", line 220, in <module>
    scripts = scripts,
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/tmpEop01P/distribute-0.6.28/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/tmpEop01P/distribute-0.6.28/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/tmp/tmpEop01P/distribute-0.6.28/pkg_resources.py", line 2029, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/tmp/tmpEop01P/distribute-0.6.28/pkg_resources.py", line 592, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (certifi 2017.4.17 (/usr/lib/python2.7/dist-packages), Requirement.parse('certifi==1.0.1'))
/var/www/stratum.local/distribute-0.6.28-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    use_setuptools()
  File "/var/www/stratum.local/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/var/www/stratum.local/distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/var/www/stratum.local/distribute_setup.py", line 116, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg."

**Comment by EmelyanovMax** [comment]
thanks. I fixed

**Comment by EmelyanovMax** [comment]
I found solution:
sudo easy_install -U distribute-0.6.28.tar.gz
sudo python setup.py install

**Comment by SnoodleBoy** [comment]
I have looked at many possible solutions to this question and tried the one above, but now of them have worked. 
I have used `sudo pip install --upgrade setuptools` 
I have updated pip and python
I have updated 'easy_install` 
I have tried all the solution i could find to the `Could not build the egg` error.
please help.

**Comment by emm-1** [comment]
Hi. What are you doing to resolve this problem please ?
