### ISSUE TITLE
ImportError: No module named server

### ISSUE THREAD

**Issue by devurandom** [slush0/stratum#6]
I ran

```
$ pip install --user stratum
```

Below is the pip.log:

```
------------------------------------------------------------
/usr/bin/pip-python3.2 run on Sun May 12 17:31:56 2013
Downloading/unpacking stratum

  Getting page https://pypi.python.org/simple/stratum/
  URLs to search for versions for stratum:
  * https://pypi.python.org/simple/stratum/
  Getting page http://blog.bitcoin.cz/stratum
  Could not fetch URL http://blog.bitcoin.cz/stratum (from https://pypi.python.org/simple/stratum/): HTTP Error 404: Not Found
  Will skip URL http://blog.bitcoin.cz/stratum when looking for download links for stratum
  Analyzing links from page https://pypi.python.org/simple/stratum/
    Found link https://pypi.python.org/packages/source/s/stratum/stratum-0.2.10.tar.gz#md5=047ef769135a05a21315b8161b36f35f (from https://pypi.python.org/simple/stratum/), version: 0.2.10
    Found link https://pypi.python.org/packages/source/s/stratum/stratum-0.2.11.tar.gz#md5=53dced78554ba4cdb18af4114f1bb4e4 (from https://pypi.python.org/simple/stratum/), version: 0.2.11
    Found link https://pypi.python.org/packages/source/s/stratum/stratum-0.2.12.tar.gz#md5=a685da0dce43263db08ae949568b0f54 (from https://pypi.python.org/simple/stratum/), version: 0.2.12
    Skipping link http://blog.bitcoin.cz/stratum (from https://pypi.python.org/simple/stratum/); not a file
  Using version 0.2.12 (newest of versions: 0.2.12, 0.2.11, 0.2.10)
  Downloading stratum-0.2.12.tar.gz

  Downloading from URL https://pypi.python.org/packages/source/s/stratum/stratum-0.2.12.tar.gz#md5=a685da0dce43263db08ae949568b0f54 (from https://pypi.python.org/simple/stratum/)
  Running setup.py egg_info for package stratum

    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/.private/USER/pip-build-USER/stratum/setup.py", line 8, in <module>
        from stratum import version
      File "stratum/__init__.py", line 1, in <module>
        from server import setup
    ImportError: No module named server

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/tmp/.private/USER/pip-build-USER/stratum/setup.py", line 8, in <module>
    from stratum import version
  File "stratum/__init__.py", line 1, in <module>
    from server import setup
ImportError: No module named server

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /tmp/.private/USER/pip-build-USER/stratum

Exception information:
Traceback (most recent call last):
  File "/usr/lib64/python3.2/site-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/lib64/python3.2/site-packages/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib64/python3.2/site-packages/pip/req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib64/python3.2/site-packages/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib64/python3.2/site-packages/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/.private/USER/pip-build-USER/stratum
```

**Comment by maxaliev** [comment]
...
